name: 重新Fork仓库
on:
  workflow_dispatch:

#  schedule:
#    - cron: 0 8 */5 * *

jobs: 
  build:
    runs-on: Ubuntu-20.04
    name: 重新Fork仓库
    steps:
    - name: 重新拉取MCydia/openwrt-package仓库
      uses: MCydia-git/github-forks-sync-action@main
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        upstream_repository: MCydia/Actions-OpenWrt
        upstream_branch: main
        target_repository: MCydia/openwrt-package     #修改成你的帐号/仓库名字
        target_branch: main                                #你仓库的分支
        force: true
        tags: false
